export const SERVICE_CATEGORIES = [
  { key: 'ELECTRICIAN', label: 'كهربائي' },
  { key: 'PLUMBER', label: 'سباك' },
  { key: 'AC_REPAIR', label: 'تصليح مكيف' },
  { key: 'WASHING_MACHINE_REPAIR', label: 'تصليح غسالة' },
  { key: 'PAINTING', label: 'صبغ' },
  { key: 'CARPENTRY', label: 'نجار' },
  { key: 'WELDING', label: 'حداد' },
  { key: 'MOVING', label: 'نقل' },
  { key: 'CLEANING', label: 'تنظيف' },
  { key: 'TUTORING', label: 'تدريس' },
  { key: 'DESIGN', label: 'تصميم' },
  { key: 'PROGRAMMING', label: 'برمجة' },
  { key: 'PHOTOGRAPHY', label: 'تصوير' },
  { key: 'MECHANIC', label: 'ميكانيكي' },
  { key: 'PHONE_REPAIR', label: 'تصليح موبايل' },
  { key: 'CAMERA_INSTALLATION', label: 'كاميرات' },
  { key: 'CONSTRUCTION_WORKER', label: 'بناء' },
  { key: 'CAR_MAINTENANCE', label: 'صيانة سيارة' },
]

export const SERVICE_CATEGORY_LABELS: Record<string, string> = {
  ELECTRICIAN: 'كهربائي',
  PLUMBER: 'سباك',
  AC_REPAIR: 'تصليح مكيف',
  WASHING_MACHINE_REPAIR: 'تصليح غسالة',
  PAINTING: 'صبغ',
  CARPENTRY: 'نجار',
  WELDING: 'حداد',
  MOVING: 'نقل',
  CLEANING: 'تنظيف',
  TUTORING: 'تدريس',
  DESIGN: 'تصميم',
  PROGRAMMING: 'برمجة',
  PHOTOGRAPHY: 'تصوير',
  MECHANIC: 'ميكانيكي',
  PHONE_REPAIR: 'تصليح موبايل',
  CAMERA_INSTALLATION: 'كاميرات',
  CONSTRUCTION_WORKER: 'بناء',
  CAR_MAINTENANCE: 'صيانة سيارة',
}