declare module 'lucide-react' {
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: number | string
    color?: string
    strokeWidth?: number | string
    absoluteStrokeWidth?: boolean
  }

  export type LucideIcon = React.ForwardRefExoticComponent<LucideProps & React.RefAttributes<SVGSVGElement>>

  export const Activity: LucideIcon
  export const Airplay: LucideIcon
  export const AlertCircle: LucideIcon
  export const AlertOctagon: LucideIcon
  export const AlertTriangle: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignJustify: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignRight: LucideIcon
  export const Anchor: LucideIcon
  export const Aperture: LucideIcon
  export const Archive: LucideIcon
  export const ArrowBigDown: LucideIcon
  export const ArrowBigLeft: LucideIcon
  export const ArrowBigRight: LucideIcon
  export const ArrowBigUp: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowDownCircle: LucideIcon
  export const ArrowDownLeft: LucideIcon
  export const ArrowDownRight: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowLeftCircle: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowRightCircle: LucideIcon
  export const ArrowUp: LucideIcon
  export const ArrowUpCircle: LucideIcon
  export const ArrowUpDown: LucideIcon
  export const ArrowUpLeft: LucideIcon
  export const ArrowUpRight: LucideIcon
  export const AtSign: LucideIcon
  export const Award: LucideIcon
  export const BarChart: LucideIcon
  export const BarChart2: LucideIcon
  export const Battery: LucideIcon
  export const BatteryCharging: LucideIcon
  export const BatteryLow: LucideIcon
  export const Bell: LucideIcon
  export const BellMinus: LucideIcon
  export const BellOff: LucideIcon
  export const BellPlus: LucideIcon
  export const BellRing: LucideIcon
  export const Bike: LucideIcon
  export const Binary: LucideIcon
  export const Bluetooth: LucideIcon
  export const Bold: LucideIcon
  export const Book: LucideIcon
  export const BookOpen: LucideIcon
  export const Bookmark: LucideIcon
  export const Box: LucideIcon
  export const BoxSelect: LucideIcon
  export const Briefcase: LucideIcon
  export const Building: LucideIcon
  export const Building2: LucideIcon
  export const Bus: LucideIcon
  export const Calculator: LucideIcon
  export const Calendar: LucideIcon
  export const Camera: LucideIcon
  export const CameraOff: LucideIcon
  export const Car: LucideIcon
  export const CarFront: LucideIcon
  export const Cast: LucideIcon
  export const Check: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckSquare: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronFirst: LucideIcon
  export const ChevronLast: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronUp: LucideIcon
  export const ChevronsDown: LucideIcon
  export const ChevronsLeft: LucideIcon
  export const ChevronsRight: LucideIcon
  export const ChevronsUp: LucideIcon
  export const Chrome: LucideIcon
  export const Circle: LucideIcon
  export const CircleDot: LucideIcon
  export const CircleEllipsis: LucideIcon
  export const CircleSlash: LucideIcon
  export const Clipboard: LucideIcon
  export const ClipboardCheck: LucideIcon
  export const ClipboardList: LucideIcon
  export const Clock: LucideIcon
  export const Cloud: LucideIcon
  export const CloudDrizzle: LucideIcon
  export const CloudLightning: LucideIcon
  export const CloudRain: LucideIcon
  export const CloudSnow: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const Codepen: LucideIcon
  export const Codesandbox: LucideIcon
  export const Coffee: LucideIcon
  export const Columns: LucideIcon
  export const Command: LucideIcon
  export const Compass: LucideIcon
  export const Component: LucideIcon
  export const Copy: LucideIcon
  export const CreditCard: LucideIcon
  export const Crop: LucideIcon
  export const Crosshair: LucideIcon
  export const Crown: LucideIcon
  export const Cube: LucideIcon
  export const Cursor: LucideIcon
  export const Database: LucideIcon
  export const Delete: LucideIcon
  export const Diameter: LucideIcon
  export const Diamond: LucideIcon
  export const Dice1: LucideIcon
  export const Dice2: LucideIcon
  export const Dice3: LucideIcon
  export const Dice4: LucideIcon
  export const Dice5: LucideIcon
  export const Dice6: LucideIcon
  export const Disc: LucideIcon
  export const Divide: LucideIcon
  export const DollarSign: LucideIcon
  export const Download: LucideIcon
  export const Droplet: LucideIcon
  export const Droplets: LucideIcon
  export const DropletCircle: LucideIcon
  export const Edit: LucideIcon
  export const Edit2: LucideIcon
  export const Edit3: LucideIcon
  export const ExternalLink: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const FastForward: LucideIcon
  export const Feather: LucideIcon
  export const File: LucideIcon
  export const FileMinus: LucideIcon
  export const FilePlus: LucideIcon
  export const FileText: LucideIcon
  export const Film: LucideIcon
  export const Filter: LucideIcon
  export const Flag: LucideIcon
  export const Folder: LucideIcon
  export const FolderOpen: LucideIcon
  export const Framer: LucideIcon
  export const Frown: LucideIcon
  export const Fuel: LucideIcon
  export const FunctionSquare: LucideIcon
  export const GalleryVerticalEnd: LucideIcon
  export const Gift: LucideIcon
  export const GitBranch: LucideIcon
  export const GitCommit: LucideIcon
  export const GitMerge: LucideIcon
  export const GitPullRequest: LucideIcon
  export const Globe: LucideIcon
  export const Grid: LucideIcon
  export const HardDrive: LucideIcon
  export const Hash: LucideIcon
  export const Headphones: LucideIcon
  export const Heart: LucideIcon
  export const HeartCrack: LucideIcon
  export const HeartOff: LucideIcon
  export const HelpCircle: LucideIcon
  export const Hexagon: LucideIcon
  export const Home: LucideIcon
  export const Image: LucideIcon
  export const Inbox: LucideIcon
  export const Info: LucideIcon
  export const Italic: LucideIcon
  export const Key: LucideIcon
  export const Layers: LucideIcon
  export const Layout: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const LayoutGrid: LucideIcon
  export const LayoutList: LucideIcon
  export const LayoutTemplate: LucideIcon
  export const Layers2: LucideIcon
  export const LifeBuoy: LucideIcon
  export const Link: LucideIcon
  export const Link2: LucideIcon
  export const Linkedin: LucideIcon
  export const List: LucideIcon
  export const Loader: LucideIcon
  export const Loader2: LucideIcon
  export const Lock: LucideIcon
  export const LogIn: LucideIcon
  export const LogOut: LucideIcon
  export const Mail: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const Maximize: LucideIcon
  export const Maximize2: LucideIcon
  export const Menu: LucideIcon
  export const MessageCircle: LucideIcon
  export const MessageSquare: LucideIcon
  export const Mic: LucideIcon
  export const Mic2: LucideIcon
  export const Minimize: LucideIcon
  export const Minus: LucideIcon
  export const Monitor: LucideIcon
  export const Moon: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const MoreVertical: LucideIcon
  export const MousePointer: LucideIcon
  export const Move: LucideIcon
  export const Music: LucideIcon
  export const Navigation: LucideIcon
  export const Navigation2: LucideIcon
  export const Octagon: LucideIcon
  export const Package: LucideIcon
  export const Paperclip: LucideIcon
  export const Pause: LucideIcon
  export const PauseCircle: LucideIcon
  export const PenTool: LucideIcon
  export const Percent: LucideIcon
  export const Phone: LucideIcon
  export const PhoneCall: LucideIcon
  export const PhoneForwarded: LucideIcon
  export const PhoneIncoming: LucideIcon
  export const PhoneMissed: LucideIcon
  export const PhoneOff: LucideIcon
  export const PhoneOutgoing: LucideIcon
  export const PieChart: LucideIcon
  export const Play: LucideIcon
  export const PlayCircle: LucideIcon
  export const Plus: LucideIcon
  export const PlusCircle: LucideIcon
  export const PlusSquare: LucideIcon
  export const Pocket: LucideIcon
  export const Power: LucideIcon
  export const Printer: LucideIcon
  export const Puzzle: LucideIcon
  export const Quote: LucideIcon
  export const Radio: LucideIcon
  export const RefreshCcw: LucideIcon
  export const RefreshCw: LucideIcon
  export const Repeat: LucideIcon
  export const Rewind: LucideIcon
  export const RotateCcw: LucideIcon
  export const RotateCw: LucideIcon
  export const Ruler: LucideIcon
  export const Save: LucideIcon
  export const Scale: LucideIcon
  export const Scan: LucideIcon
  export const Search: LucideIcon
  export const Send: LucideIcon
  export const Server: LucideIcon
  export const Settings: LucideIcon
  export const Share: LucideIcon
  export const Share2: LucideIcon
  export const Shield: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldCheck: LucideIcon
  export const ShieldMinus: LucideIcon
  export const ShieldOff: LucideIcon
  export const ShieldPlus: LucideIcon
  export const ShoppingBag: LucideIcon
  export const ShoppingCart: LucideIcon
  export const Shuffle: LucideIcon
  export const Sidebar: LucideIcon
  export const SkipBack: LucideIcon
  export const SkipForward: LucideIcon
  export const Slack: LucideIcon
  export const Slash: LucideIcon
  export const Smartphone: LucideIcon
  export const Smile: LucideIcon
  export const Speaker: LucideIcon
  export const Sparkles: LucideIcon
  export const Square: LucideIcon
  export const Star: LucideIcon
  export const StopCircle: LucideIcon
  export const Sun: LucideIcon
  export const Sunrise: LucideIcon
  export const Sunset: LucideIcon
  export const Tablet: LucideIcon
  export const Tag: LucideIcon
  export const Target: LucideIcon
  export const Terminal: LucideIcon
  export const Thermometer: LucideIcon
  export const ThermometerSun: LucideIcon
  export const ThumbsUp: LucideIcon
  export const ThumbsDown: LucideIcon
  export const ToggleLeft: LucideIcon
  export const ToggleRight: LucideIcon
  export const Tool: LucideIcon
  export const Trash: LucideIcon
  export const Trash2: LucideIcon
  export const TreePine: LucideIcon
  export const TrendingUp: LucideIcon
  export const Laptop: LucideIcon
  export const Brain: LucideIcon
  export const TrendDown: LucideIcon
  export const Triangle: LucideIcon
  export const Truck: LucideIcon
  export const Tv: LucideIcon
  export const Type: LucideIcon
  export const Umbrella: LucideIcon
  export const Underline: LucideIcon
  export const Undo: LucideIcon
  export const Undo2: LucideIcon
  export const Unlink: LucideIcon
  export const Unlock: LucideIcon
  export const Upload: LucideIcon
  export const UploadCloud: LucideIcon
  export const User: LucideIcon
  export const UserCheck: LucideIcon
  export const UserMinus: LucideIcon
  export const UserPlus: LucideIcon
  export const UserX: LucideIcon
  export const Users: LucideIcon
  export const WashingMachine: LucideIcon
  export const Megaphone: LucideIcon
  export const FileText: LucideIcon
  export const GraduationCap: LucideIcon
  export const Palette: LucideIcon
  export const Code: LucideIcon
  export const Camera: LucideIcon
  export const CarFront: LucideIcon
  export const Building: LucideIcon
  export const Hammer: LucideIcon
  export const Truck: LucideIcon
  export const Sparkles: LucideIcon
  export const Zap: LucideIcon
  export const Droplets: LucideIcon
  export const Wind: LucideIcon
  export const Paintbrush: LucideIcon
  export const Shield: LucideIcon
  export const Check: LucideIcon
  export const XCircle: LucideIcon
  export const Video: LucideIcon
  export const VideoOff: LucideIcon
  export const Voicemail: LucideIcon
  export const Volume: LucideIcon
  export const Volume2: LucideIcon
  export const VolumeX: LucideIcon
  export const Wallet: LucideIcon
  export const Wand2: LucideIcon
  export const Watch: LucideIcon
  export const Waves: LucideIcon
  export const Webcam: LucideIcon
  export const Wifi: LucideIcon
  export const Wind: LucideIcon
  export const WrappingPaper: LucideIcon
  export const Wrench: LucideIcon
  export const X: LucideIcon
  export const XCircle: LucideIcon
  export const XSquare: LucideIcon
  export const Zap: LucideIcon
  export const ZoomIn: LucideIcon
  export const ZoomOut: LucideIcon
}